### ISSUE TITLE
Identical function names for different code sections

### ISSUE THREAD

**Issue by janbbeck** [cmu-sei/pharos#123]
I have the situation that two different addresses have been given the same function names after applying ooanlyzer in Ghidra.

For example, at address 0x00437c66 the decompilation gives a function of 

```
cls_0x8b02e8 * __thiscall OOAnalyzer::cls_0x8b02e8::cls_0x8b02e8(cls_0x8b02e8 *this)
```
and at address 0x004222e0
```
cls_0x8b02e8 * __thiscall OOAnalyzer::cls_0x8b02e8::cls_0x8b02e8(cls_0x8b02e8 *this)

```
with different code contents.

Maybe these are virtual methods from classes that inherit from a top level class? But should they then not get their own class name?
address 0x8b02e8 is just data according to ghidra:
```
                             DAT_008b02e8                                    XREF[1]:     cls_0x8b02e8:004fcc32(*)  
        008b02e8 43              ??         43h    C                                         ?  ->  006c5143
        008b02e9 51              ??         51h    Q
        008b02ea 6c              ??         6Ch    l
        008b02eb 00              ??         00h
```
but there is a reference to 0x004fcc32, which is another instance of the same function:
```
cls_0x8b02e8 * __thiscall OOAnalyzer::cls_0x8b02e8::cls_0x8b02e8(cls_0x8b02e8 *this)
```
with yet other code contents.

My c++-fu may be weak. I'll gladly accept some education.

Thanks.

I'm adding some screen shots in the hope that they add clarity

![Screenshot from 2020-07-18 19-46-29](https://user-images.githubusercontent.com/11450961/87864092-cc83ed80-c931-11ea-95d6-a39460deaec9.png)

![Screenshot from 2020-07-18 20-04-56](https://user-images.githubusercontent.com/11450961/87864103-0d7c0200-c932-11ea-89cc-863297a2294c.png)

**Comment by sei-eschwartz** [comment]
I think there are two concerns here.

* All constructors on a class are named the same.  Is this a bug?  What does Ghidra do for overloaded functions?
* Are these methods really on the same class?  If the decompiler is right about the parameters, I don't think they can be.  This could possibly be a new sanity rule: you can only have one constructor on a class for a given set of parameters.

Can you share the exe and ooanalyzer outputs, either publicly or privately?

Sent from Workspace ONE Boxer

On Jul 18, 2020 8:07 PM, Jan Beck <notifications@github.com> wrote:

I have the situation that two different addresses have been given the same function names after applying ooanlyzer in Ghidra.

For example, at address 0x00437c66 the decompilation gives a function of

cls_0x8b02e8 * __thiscall OOAnalyzer::cls_0x8b02e8::cls_0x8b02e8(cls_0x8b02e8 *this)


and at address 0x004222e0

cls_0x8b02e8 * __thiscall OOAnalyzer::cls_0x8b02e8::cls_0x8b02e8(cls_0x8b02e8 *this)



with different code contents.

Maybe these are virtual methods from classes that inherit from a top level class? But should they then not get their own class name?
address 0x8b02e8 is just data according to ghidra:

                             DAT_008b02e8                                    XREF[1]:     cls_0x8b02e8:004fcc32(*)
        008b02e8 43              ??         43h    C                                         ?  ->  006c5143
        008b02e9 51              ??         51h    Q
        008b02ea 6c              ??         6Ch    l
        008b02eb 00              ??         00h


but there is a reference to 0x004fcc32, which is another instance of the same function:

cls_0x8b02e8 * __thiscall OOAnalyzer::cls_0x8b02e8::cls_0x8b02e8(cls_0x8b02e8 *this)


with yet other code contents.

My c++-fu may be weak. I'll gladly accept some education.

Thanks.

I'm adding some screen shots in the hope that they add clarity

[Screenshot from 2020-07-18 19-46-29]<https://user-images.githubusercontent.com/11450961/87864092-cc83ed80-c931-11ea-95d6-a39460deaec9.png>

[Screenshot from 2020-07-18 20-04-56]<https://user-images.githubusercontent.com/11450961/87864103-0d7c0200-c932-11ea-89cc-863297a2294c.png>

**Comment by janbbeck** [comment]
Same exe I have been using all along to test ooanalyzer. Glad to share the files
[ooprog-results_V9.pl.zip](https://github.com/cmu-sei/pharos/files/4943873/ooprog-results_V9.pl.zip)
[V9.ooanalyzer.json.zip](https://github.com/cmu-sei/pharos/files/4943875/V9.ooanalyzer.json.zip)
[V9.exe.zip](https://github.com/cmu-sei/pharos/files/4943876/V9.exe.zip)

The ooprog.log file is very large, even compressed, and github wont let me upload it. But if you feel it's important I can put it up somewhere else.

Thanks

**Comment by sei-eschwartz** [comment]
Thanks. I'll let you know if we need the prolog log, but probably not.

Sent from Workspace ONE Boxer

On Jul 19, 2020 11:11 AM, Jan Beck <notifications@github.com> wrote:

Same exe I have been using all along to test ooanalyzer. Glad to share the files
ooprog-results_V9.pl.zip<https://github.com/cmu-sei/pharos/files/4943873/ooprog-results_V9.pl.zip>
V9.ooanalyzer.json.zip<https://github.com/cmu-sei/pharos/files/4943875/V9.ooanalyzer.json.zip>
V9.exe.zip<https://github.com/cmu-sei/pharos/files/4943876/V9.exe.zip>

The ooprog.log file is very large, even compressed, and github wont let me upload it. But if you feel it's important I can put it up somewhere else.

Thanks

**Comment by sei-eschwartz** [comment]
I am looking at this some more.  According to OOAnalyzer, 0x8b02e8 is a VFTable, which is then used as a class identifier.

@janbbeck Just to clarify, is your complaint that there are multiple functions in Ghidra with the same name?  If there are multiple constructors identified on the same class, how would you like them to be named?

There are in fact many more than three constructors identified for class 0x8b02e8.  I don't see how this could be right.  I will let @sei-ccohen weigh in.  But my gut feeling is that there are a lot of derived classes that were incorrectly merged together.

There are some other odd things as well.  OOAnalyzer did not seem to set 0x8b02e8 and other vftables as vftables in Ghidra (though OOAnalyzer itself did detect them).

**Comment by sei-eschwartz** [comment]
Here is why the VFTable is not set correctly:
```
2020-06-11 10:44:55 WARN  (OOAnalyzer) Could not create virtual function table at 0x008b02e8: ghidra.program.model.util.CodeUnitInsertionException: Conflicting data exists at address 008b02ec to 008b02ef
```
Ghidra already created a pointer there.  We should probably delete it.

**Comment by sei-eschwartz** [comment]
Ah, we remove any data at the start of the vftable.  But don't remove data "inside" the vftable.

**Comment by janbbeck** [comment]
> I am looking at this some more. According to OOAnalyzer, 0x8b02e8 is a VFTable, which is then used as a class identifier.
> 
> @janbbeck Just to clarify, is your complaint that there are multiple functions in Ghidra with the same name? If there are multiple constructors identified on the same class, how would you like them to be named?
> 
> There are in fact many more than three constructors identified for class 0x8b02e8. I don't see how this could be right. I will let @sei-ccohen weigh in. But my gut feeling is that there are a lot of derived classes that were incorrectly merged together.
> 
> There are some other odd things as well. OOAnalyzer did not seem to set 0x8b02e8 and other vftables as vftables in Ghidra (though OOAnalyzer itself did detect them).

My concern is less that there are identical function names, but more that there are identical constructors (identical function names + arguments) for a single class

**Comment by sei-ccohen** [comment]
Sorry, I should have weighed in (publicly) on this issue earlier.  My theory is that it's entirely possible that the parameters are not in fact identical.   The decompiler could for example easily confuse these cases:

Class::Class(OtherClassA x), Class::Class(OtherClassB x), Class::Class(OtherClassC x)

and so on...  It's even possible that there's a very large number of such constructors because there was a template such as:

template <T> Class::Class(T x) { ... }

I'm not saying that's what happened here.  Just that I'd want to see more evidence of a problem before assuming that having lots of constructors implies a logic problem in OOAnalyzer.  I also haven't looked in much detail at the details you have provided since sei-eschwartz was handling most of the issue.

**Comment by janbbeck** [comment]
> Sorry, I should have weighed in (publicly) on this issue earlier. My theory is that it's entirely possible that the parameters are not in fact identical. The decompiler could for example easily confuse these cases:
> 
> Class::Class(OtherClassA x), Class::Class(OtherClassB x), Class::Class(OtherClassC x)
> 
> and so on... It's even possible that there's a very large number of such constructors because there was a template such as:
> 
> template Class::Class(T x) { ... }
> 
> I'm not saying that's what happened here. Just that I'd want to see more evidence of a problem before assuming that having lots of constructors implies a logic problem in OOAnalyzer. I also haven't looked in much detail at the details you have provided since sei-eschwartz was handling most of the issue. I see now that you did upload results and exes, so I'll look more at the actual facts tomorrow. ;-)

Your examples 

Class::Class(OtherClassA x), Class::Class(OtherClassB x), Class::Class(OtherClassC x)

are all valid, of course. But what I see in the namespace now is several instances of (equivalently)

Class::Class(OtherClassA x),  Class::Class(OtherClassA x),  Class::Class(OtherClassA x), i.e.

several functions with different code contents having this exact name:

cls_0x8b02e8 * __thiscall OOAnalyzer::cls_0x8b02e8::cls_0x8b02e8(cls_0x8b02e8 *this)

Can this be intended?

**Comment by sei-mwd** [comment]
Just to be complete, I can think of at least four ways we could legitimately end up with two things that look like constructors for the same object with identical parameters:

1. Constructor A takes and object pointer, O,  and constructor B takes an object pointer, P, where P derives from O.  If only O behavior is used on P by B, then we can't necessarily tell the difference in the binary.
2. Constructors for objects A and B, where B inherits from A, they have no virtual methods, and B's constructor does nothing that could not be done in an A.
3. Two constructors on an object where at least one of them takes a second "tag" parameter, where a tag is an empty class.  (Not uncommon in C++.)  The second parameter disappears in the compilation since it's just used to choose between otherwise identical constructors.
4. A function or static method that calls a constructor for an object and returns a pointer to it.  If the constructor is inlined, there may be no way to distinguish this function or method from a constructor.

**Comment by cfcohen** [comment]
So...  I've actually looked at this a little now (instead of just reading the commentary).   I think it's pretty clear that 0x8b02e8 is in fact a virtual function table.   There are several references to external CWnd::xxx methods in MFC42.DLL In there.   So that's probably a user-derived class with CWnd as a base.     I think the legitimate constructor is at 0x4fcc00, which properly installs that VFTable into the object.

But it's unclear to me right now how these other methods got associated with that class.    They do appear to be constructors since they appear to be installing _different_ VFTables into their respective objects.   They also appear to be derivatives of CWnd, and possibly 0x8b02e8, which would explain why got confused and merged them all together.    That's probably why that class is gigantic. :-(  What definitely signals that something is wrong here (and we should try to write a new rule for this) is that these methods can't be constructors on a class that has a VFTable (0x8b02e8) with actually installing that VFTable into the object.   Installing a different VFTable (as these methods do) necessitates that they are constructors on a different class.   I'll see if I can write a new rule and test it, but V9 is obviously a big file so it'll take a while.

**Comment by cfcohen** [comment]
Hmm.  We've already got this rule. :-(   

https://github.com/cmu-sei/pharos/blob/master/share/prolog/oorules/rules.pl#L2466

So the question really is:  Why didn't it trigger properly, and prevent these classes from being merged? For example,

Instruction 0x422312 installs 0x8a22f0 in method 0x4222e0
Instruction 0x437c98 installs 0x8a3dc8 in method 0x437c66
Instruction 0x4fcc32 installs 0x8b02e8 in method 0x4fcc00

And while I can't easily prove that we knew each of those were VFTableWrites without the full log, I can prove that we knew that they were VFtables by the end of the analysis:

$ grep finalVFTable ooprog-results_V9.pl | grep -e 0x8a22f0 -e 0x8a3dc8 -e 0x8b02e8
finalVFTable(0x8a22f0, 0xf0, 0xf0, 0, '').
finalVFTable(0x8a3dc8, 0xf4, 0xf4, 0, '').
finalVFTable(0x8b02e8, 0xe8, 0xe8, 0, '').

And yet they all ended up on the same class (0x8b02e8).

So that rule should have blocked the merger...   Something more complicated must be going on.   Perhaps it's related to ordering and the triggers?   Do we need a sanity check rule to prevent this condition _post_ merger?   How did we fail to detect the condition before the merger?

**Comment by cfcohen** [comment]
More curious results...  @sei-eschwartz ran this file to completion on Jul 3 & 4, and that run did NOT merge these methods, instead assigning them to separate classes as OOAnalyzer should have.   Your ticket is _more_ recent than that though.   What day did you run the OOAnalyzer on, and were you running the latest version OOAnalyzer at that time to your knowledge?

**Comment by sei-eschwartz** [comment]
@cfcohen It's very likely the version of OOAnalyzer I used on July 4th was not publicly released at that time.

Anyway, it seems very likely that we have fixed the problem in one of our recent releases.  I am attaching my `V9.exe.results` file.  I don't have the json file handy because we're about to change the format, but you can just rerun `oojson`.

[V9.exe.results.zip](https://github.com/cmu-sei/pharos/files/4961485/V9.exe.results.zip)

**Comment by sei-eschwartz** [comment]
I am going to close this issue for now under the hope that the new file fixes all your concerns.  Please re-open if it turns out there is still something that doesn't look right.

**Comment by sei-eschwartz** [comment]
Also, we just pushed a new release with the new json format.  Here's the json in that new format.
[V9.exe.json.zip](https://github.com/cmu-sei/pharos/files/4961736/V9.exe.json.zip)

**Comment by janbbeck** [comment]
Thank you for that json file - and all the comments in this thread. This looks much more sane to me. 

Upon looking at the namespace further, I still have some questions. There are similarly many functions in the namespace for CWnd. for example, at 

0x00444ab1
there is 
CWnd * __thiscall CWnd(CWnd *this,int param_1)
and at
0x004cd518
there is
CWnd * __thiscall CWnd(CWnd *this,int param_1)

Again I see two functions with the same name and parameters. Also, the constructors for CWnd are certainly not inside the program code. And if any class inherits from CWnd, then it should have a different name shouldn't it?

Or am I misunderstanding something?

![Screenshot from 2020-07-23 16-38-48](https://user-images.githubusercontent.com/11450961/88336483-0fafd900-cd03-11ea-8691-81f903a225da.png)

**Comment by sei-eschwartz** [comment]
We will take a look

**Comment by sei-eschwartz** [comment]
I think you're right @janbbeck.  `CWnd::CWnd` does not look to me like it is in the binary.  Instead, we seem to have incorrectly merged a method from `CWnd` into the class.

Possible solution:
- If we have the name from import symbols for one method, all methods on the class should have imported names?  Could be a not NOTMergeClasses rule or sanity checking rule.

What do you think @sei-ccohen?

**Comment by sei-ccohen** [comment]
I'm pretty sure that the CWnd methods are _correctly_ merged into the class.    My theory here is that I think we have a heuristic to name a class based on the class names of any methods that it calls out to.  Normally, a class with a method named "Cls::m()" would be named "Cls".  Normally, this does well at naming classes that are completely (or nearly completely) external.

In this particular case that results in a bunch of classes all named "CWnd", which is confusing.    I think we should probably name them "CWnd1", "Cwnd2", "CWnd3", etc.   @sei-eschwartz and I will discuss.

**Comment by sei-eschwartz** [comment]
So we haven't forgot about this, but haven't been updating the github issue very well.

So our conclusion is that we are _incorrectly_ merging the methods into the class because the class inherits from an imported class.  This is important, because we don't see some things in an imported class (like the constructor installing a vftable), which changes the results that fire.  So we modified a rule to help us detect inheritance in that situation.

We also added the rule that I suggested above, which is to not allow classes with a mix of imported and non-imported methods.

**Comment by sei-eschwartz** [comment]
I just got the updated results.  
[V9.exe.json.zip](https://github.com/cmu-sei/pharos/files/5007370/V9.exe.json.zip)

I haven't been able to investigate much at all yet.  Cwnd no longer appears in the class list under `OOAnalyzer`.  I'm not 100% clear on what that means yet.

**Comment by sei-eschwartz** [comment]
Disregard for now.  Something has clearly gone wrong with the generation of my facts file.

**Comment by sei-eschwartz** [comment]
I forgot to include `mfc42.json` :-(

**Comment by janbbeck** [comment]
Thanks for the update! Good to know I wasn't crazy :P

**Comment by sei-eschwartz** [comment]
Just so know this has been running for several days now.  I can't remember if it took this long last time or not.

**Comment by janbbeck** [comment]
including the defs for mfc did drastically increase run time for me as well.

**Comment by sei-eschwartz** [comment]
Haven't tested yet but got the results back

[V9.zip](https://github.com/cmu-sei/pharos/files/5078677/V9.zip)

**Comment by janbbeck** [comment]
Thanks!

**Comment by sei-eschwartz** [comment]
Sadly it doesn't look like we figured out the inheritance correctly for 0x444ab1.  I'll look at that more.

**Comment by janbbeck** [comment]
Ok, thanks for letting me know.

**Comment by sei-eschwartz** [comment]
Looking at this more now.  There are a lot of oddities just from looking at 0x444ab1

- According to Ghidra, `FUN_00819eff` is called by the constructor 0x444ab1 returns a `cls_0x444ab1 *`
- `GetDlgItem` is a thunk to an imported `CWnd::GetDlgItem` but isn't renamed.
- Member at 0x1ec is passed to method 0x5c30a7 on `cls_0b7b78` but we did not detect a member there at all
- Method 0x4062e0 on class 0x8b7b78 takes a pointer to this but again we do not detect inheritance or embedding

**Comment by sei-eschwartz** [comment]
I'm not convinced that 0x444ab1 is a constructor at all.  There are also no xrefs to it.  So I think the failure with 0x444ab1 is that it's not connected to the proper class (still tbd).

**Comment by sei-eschwartz** [comment]
Looks like we are detecting the inheritance to imported `CWnd`.  One example is `cls_0x89f890`.

I'd like @sei-ccohen to look at 0x444ab1 some more because some of it looks very wrong to me but I think the issue with `CWnd` does actually look resolved to me.

**Comment by cfcohen** [comment]
There seems to me to be quite a lot wrong with 0x444ab1.   Personally, I'm nearly certain that it is not a constructor either.   I'm fairly certain that Ghidra's warning which reads "Could not reconcile some variable overlaps" is code for "Ghidra got confused and the decompilation is garbage".   You get different numbers of parameters if you fiddle with the calling convention several times.  Something strange is going on with the function analysis for sure.  This is further supported by the fact that Pharos reported "callingConvention(0x444ab1, invalid)." in the facts file.  This makes it very hard to tell what's "really true" from a casual analysis.

As for the OOAnalyzer decision to call it a constructor -- That's easier to explain.  According to our "facts"  the function returns itself, has no calls to it before object construction, has no calls to it after object destruction, and doesn't read any members before initialization.    This very weak set of requirements are all "absence of evidence" that would prevent it from being a constructor.  The only "positive" evidence is "returnsSelf" which is incorrect, and appears to have been caused by whatever is confusing Ghidra.   This fact should really be called "canReturnSelf" because of how some Pharos internals work.   The three negative facts aren't that hard to generate "accidentally".   Then because it's nearly impossible to _prove_ that a method is a constructor, we have some very liberal guessing rules that turn most functions withe these facts into constructors.   In this particular case there was nothing to prevent us from guessing that the method was a constructor because it was the only method on the class.

**Comment by edmcman** [comment]
If I recall correctly, there are no calls to it at all. Maybe that should be an additional requirement to guess that it is a constructor?

**Comment by janbbeck** [comment]
I am curious if you guys had any more internal discussions about this.

**Comment by sei-eschwartz** [comment]
No, we haven't discussed further.  As @sei-ccohen pointed out, a lot of the problems with 0x444ab1 are probably because OOAnalyzer did not detect the calling convention.  Though it looks like thiscall to me, so I'm not sure why it didn't detect it.

Is there anything in particular you were concerned about?  It looked like the original issue was fixed as far as we could see.

**Comment by sei-eschwartz** [comment]
To be more precise, it looks like the `CWnd` issue was fixed.  I just looked and `cls_0x8c2d68` has a fairly ridiculous number of constructors and destructors on it.

**Comment by sei-eschwartz** [comment]
The vftable for class cls_0x8c2d68 is 0x8aa260.  According to ghidra, it is only installed by the constructor 0x47349f at 0x47375c and a destructor.

It seems to me that the dozens of other "constructors" on class cls_0c2d68 are either not constructors or are not on the same class because they don't install the vftable.  In other words:

If constructor C installs vftable V, any other constructor C' on the same class must also install vftable V.

Thoughts @sei-ccohen?  It seems like this should generally be true, though maybe the compiler could optimize a vftable installation in some cases but not others?  I could definitely see this being true for destructors, but less so for constructors.

0x47349f is also pretty weird.  It looks to me like it's constructing a ton of embedded (or inherited) objects, which we do not correctly detect.

**Comment by janbbeck** [comment]
There is nothing in particular I am concerned about. I was wanting to see if I should give it another run and check out the results for other problems, or if you guys were still working on issues known with this binary.

**Comment by sei-eschwartz** [comment]
We are now looking into the above problems I noticed, but yes, you should definitely check the results for other problems.

**Comment by sei-eschwartz** [comment]
We just added the above rule I talked about.  I have not had a chance to rerun `V1.exe` yet though.

**Comment by janbbeck** [comment]
Thanks for the update. I've been too busy with work to rerun this. I hope to get to it in the next few days.

**Comment by sei-eschwartz** [comment]
Well, some good news is that the new version is a lot faster!  It now ran overnight for me.

[V9.exe.json.zip](https://github.com/cmu-sei/pharos/files/5275873/V9.exe.json.zip)

**Comment by janbbeck** [comment]
Awesome! I perused that file, and I found some behavior I don't understand.
What I expected to see is of the example:
`OOAnalyzer::cls_0x8e68f4::cls_0x8e68f4`
The class name has has two child nodes which are different constructors, both called `cls_0x8e68f4`
Many other classes have a single child node with just one constructor having the same name as the class. Also expected.

But also many of the cls_ names in the symbol tree only have a single child member of the same name as a but labeled as a method or virtual method. For example:
`OOAnalyzer::cls_0x584f00::meth_0x584f00`
`OOAnalyzer::cls_0x5688aa::virt_meth_0x5688aa`
is the meth_ a constructor? Or maybe 0x584f00 is just there for other classes to inherit from? but where is its constructor? Surely there has to be at least a default constructor for a class? I guess virt_meth is the same but for virtual inheritance?

And some have only got a destructor:
`OOAnalyzer::cls_0x8e5818::~cls_0x8e5818`

for that class, going to the named address shows:
`cls_0x8e5818::vftable_8e5818_008e5818`
I guess the constructor is in a virtual function table, but shouldn't there be a child node pointing to that?

I am probably displaying my ignorance of C++ compilation internals. If all this is expected, I would appreciate some education.

**Comment by sei-ccohen** [comment]
So in general, this is an artifact of what happens when OOAnalyzer fails to reach the correct conclusions.   At a very high-level the algorithm in the Prolog code is to place every method in a class by itself and then look for "proof" that two methods are in fact the same class via our Prolog rules.    After exhausting all of the sound rules, we start making educated guesses about class merges based on rules that simply suggest that two methods are on the same class.   For example, we might have a rule that "knows" that a method is on either the Derived class or the Base class, and we'll "try" each.

Particularly when things begin to go off the rails a bit, perhaps because of incorrect guess that we were unable to detect as incorrect,  we start ending up with cases where the method isn't permitted on either the Base class or the Derived class.  :-(   In these cases, the function tends to end up just being "left" on the class by itself.   In some cases, the problem is that there was no suggestion that the method was associated with any class at all, and so we never even tried to assign the method to a class, even through a guess.

As we near the final stage of reporting we usually discard these "singleton methods" that are in a class by themselves just to reduce worthless clutter in the results.   Recently we've gotten better at detecting VFTables from RTTI and some related issues that technically make these methods more than just a single method (e.g. it's a method and a VFTable on the class).    That's causing them to be reported more frequently, and may be related to you seeing them more.

As a developer of OOAnlayzer, these singleton method classes are a sign something has gone wrong, and I usually start by asking myself which class it should have been merged with, how _I_ knew that, and why OOAnalyzer didn't figure that out.  As our rules have gotten better it often turns into cases that are quite complicated, such as me not being able to figure it out myself, or there being something unrelated that went wrong earlier in the process that prevented OOAnalyzer from doing the right thing when it tried to.

A few other comments on your message.... It's pretty common for destructors to fail to get attached to the correct class.  A failure to associate virtual methods correctly is rarer and more surprising.   The constructor CANNOT be in the virtual function table.  That's not allowed by C++.  If the object exists it doesn't need to be constructed, and if it doesn't there's no VFTable to refer to.  what you probably mean to say is the reference to the VFTable should also be in the constructor somewhere, and that's correct.   Unfortunately, something else strange probably happened like that constructor was inlined into some other constructor, and so it doesn't exist as a separate function at all...   This may mean that a class containing nothing but the destructor could actually be correct.   And so the endless complexity continues...

**Comment by janbbeck** [comment]
Thank you very much for that detailed explanation!

**Comment by sei-ccohen** [comment]
Also, since you're probably not watching every open issue like we are, this post I just made a short while ago:
 
https://github.com/cmu-sei/pharos/issues/136#issuecomment-698990394

May be interesting to you.   I don't know whether V9 is exhibiting the "reused implementation" problem or not because sei-eschwartz has been handling most of the analysis.

**Comment by sei-eschwartz** [comment]
I am not sure either way. We should look at the singleton classes and see if we can figure out where they belong.

Sent from Workspace ONE Boxer

On Sep 25, 2020 12:11 PM, Cory Cohen <notifications@github.com> wrote:

Also, since you're probably not watching every open issue like we are, this post I just made a short while ago:

#136 (comment)<https://github.com/cmu-sei/pharos/issues/136#issuecomment-698990394>

May be interesting to you. I don't know whether V9 is exhibiting the "reused implementation" problem or not because sei-eschwartz has been handling most of the analysis.
