### ISSUE TITLE
Member class throwing when calling mbr.getOffset() from OOAnalyzer.java.

### ISSUE THREAD

**Issue by Jonathan-Greve** [cmu-sei/pharos#201]
EDIT: I got it working by deleting an entry/class in the json file. See my comment below.
-------------------------------

I have my .json file that I got by running OOanalyzer. When I import it into the tool in Ghidra it throws an exception:
**java.lang.NumberFormatException: Sign character in wrong position**

Interestingly it throwns on a different member each time I run the tool. For example here it throws on <lambda_1c7d96af0f0b63f6b7070c698dcc1b90> at offset 8

the previous time I've tried to run it's thrown at:
0x706bd0
0x7a02c0
0xa037ec
0x9d2548
0x99db20
0x8785b0

the .json file is approximately 150000 lines long on a 8MB program with ~ 18000 functions.

Interestingly enough I got it to run correctly in Ghidra after deleting ~half of the lines in the .json file.
But I would like all classes imported if possible.

The relevant log is:
=============================================================
2022-01-03 16:27:56 DEBUG (OOAnalyzer) Adding member [name=mbr_0x828, type=, struc=, parent=false, offset=0x828, size=4] to class cls_0x4268bc at offset 2088  
2022-01-03 16:27:56 DEBUG (OOAnalyzer) Clearing component   0  0  undefined  1  null  null  
2022-01-03 16:27:56 DEBUG (OOAnalyzer) Clearing component   1  1  undefined  1  null  null  
2022-01-03 16:27:56 DEBUG (OOAnalyzer) Clearing component   2  2  undefined  1  null  null  
2022-01-03 16:27:56 DEBUG (OOAnalyzer) Clearing component   3  3  undefined  1  null  null  
2022-01-03 16:27:56 DEBUG (OOAnalyzer) Adding member [name=mbr_0x0, type=, struc=, parent=false, offset=0x0, size=4] to class <lambda_1c7d96af0f0b63f6b7070c698dcc1b90> at offset 0  
2022-01-03 16:27:56 DEBUG (OOAnalyzer) Clearing component   1  4  undefined  1  null  null  
2022-01-03 16:27:56 DEBUG (OOAnalyzer) Clearing component   2  5  undefined  1  null  null  
2022-01-03 16:27:56 DEBUG (OOAnalyzer) Clearing component   3  6  undefined  1  null  null  
2022-01-03 16:27:56 DEBUG (OOAnalyzer) Clearing component   4  7  undefined  1  null  null  
2022-01-03 16:27:56 DEBUG (OOAnalyzer) Adding member [name=mbr_0x4, type=, struc=, parent=false, offset=0x4, size=4] to class <lambda_1c7d96af0f0b63f6b7070c698dcc1b90> at offset 4  
2022-01-03 16:27:56 DEBUG (OOAnalyzer) Clearing component   2  8  undefined  1  null  null  
2022-01-03 16:27:56 DEBUG (OOAnalyzer) Clearing component   3  9  undefined  1  null  null  
2022-01-03 16:27:56 DEBUG (OOAnalyzer) Clearing component   4  10  undefined  1  null  null  
2022-01-03 16:27:56 DEBUG (OOAnalyzer) Clearing component   5  11  undefined  1  null  null  
2022-01-03 16:27:56 DEBUG (OOAnalyzer) Adding member [name=mbr_0x8, type=, struc=, parent=false, offset=0x8, size=4] to class <lambda_1c7d96af0f0b63f6b7070c698dcc1b90> at offset 8  
2022-01-03 16:27:56 ERROR (BackgroundCommandTask) Command Failure: An unexpected error occurred while processing the command: OOAnalyzer Import java.lang.NumberFormatException: Sign character in wrong position
	at java.base/java.lang.Integer.decode(Integer.java:1425)
	at kaiju.tools.ooanalyzer.jsontypes.Member.getOffset(Member.java:99)
	at kaiju.tools.ooanalyzer.OOAnalyzer.analyzeMembers(OOAnalyzer.java:1310)
	at kaiju.tools.ooanalyzer.OOAnalyzer.lambda$analyzeClasses$7(OOAnalyzer.java:453)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.WhileOps$1$1.accept(WhileOps.java:99)
	at java.base/java.util.HashMap$EntrySpliterator.tryAdvance(HashMap.java:1785)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at kaiju.tools.ooanalyzer.OOAnalyzer.analyzeClasses(OOAnalyzer.java:447)
	at kaiju.tools.ooanalyzer.OOAnalyzerGhidraPlugin$ImportCommand.cmdConfigureAndExecute(OOAnalyzerGhidraPlugin.java:201)
	at kaiju.tools.ooanalyzer.OOAnalyzerGhidraPlugin$ImportCommand.applyTo(OOAnalyzerGhidraPlugin.java:134)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:102)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:319)
	at java.base/java.lang.Thread.run(Thread.java:829)
 
2022-01-03 16:27:56 ERROR (ToolTaskManager) OOAnalyzer Import Failed: Unspecified error occurred.  
2022-01-03 16:27:56 DEBUG (ToolTaskManager) Mon Jan 03 16:27:56 CST 2022 Background processing complete (255.141 secs)
-=============================================================-

The relevant code is:
-----------------------------------------------------------------------
**OOAnalyzer.java** on line 1310
**1293**    private void analyzeMembers(OOAnalyzerClassType ooaType, Structure ghidraType) {
**1294**   
**1295**        if (!classSymbolMap.containsKey(ghidraType)) {
**1296**         Msg.warn(this, "Skipping " + ooaType.getName() + " because there is no associated symbol.");
**1297**         Msg.warn(this, "The Ghidra type was " + ghidraType.getName());
**1298**          return;
**1299**        }
**1300** 
**1301**     // If there are members for this type, process them
**1302**     Collection<Member> members = ooaType.getMembers();
**1303**        for (Member mbr : members) {
**1304** 
**1305**          if (mbr.getBase()) {
**1306**            Msg.trace (this, "Skipping member " + mbr.getName() + " because it was defined on the base class.");
**1307**            continue;
**1308**          }
**1309** 
**1310**          if (mbr.getOffset() == Member.INVALID_OFFSET) {
**1311**            Msg.error(this, "Cannot add member " + mbr.getName() + " due to invalid offset");
**1312**            continue;
**1313**          }

**Member.java**
 **98**      public Integer getOffset() {
 **99**          return Integer.decode (offset);
**100**     }

Perhaps some exception handling could be added to the getOffset() method so that it returns INVALID_OFFSET instead of throwing.

**Comment by Jonathan-Greve** [comment]
After some debbuging I found the offending class in the json file. 1 of out 869 classes caused the analysis to fail. After deleting it from the json file the kaiji plugin ran perfect and imported 868 classes 😄 

If you want to look more into the issue I can share the .exe file and output.json. Otherwise we can close the issue.

**Comment by sei-eschwartz** [comment]
Can you share the part of the JSON that caused the problem?

**Comment by Jonathan-Greve** [comment]
[output_modified.txt](https://github.com/cmu-sei/pharos/files/7804716/output_modified.txt)

It seems to be the line: **"offset":"0x-1ab",**
where it seems like the minus sign is in the wrong position.

If I change it to **"offset":"-0x1ab",** then the kaiji plugin runs perfectly and import all classes from the JSON file.

I originally generated the JSON file using the command: **ooanalyzer --maximum-memory=32000 --json=/tmp/output.json input.exe**

**Comment by sei-eschwartz** [comment]
Is it possible for you to share your .exe and/or facts file too?  I don't think those offsets should ever be negative, so this is more than a printing/formatting problem.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sei-eschwartz** [comment]
From the results file:

`finalEmbeddedObject(0x711300, -0x1ab, 0x7116e0, likely).`

**Comment by sei-eschwartz** [comment]
The problem ultimately stems from this bogus fact: `funcOffset(0x7115db, 0x711300, 0x7116e0, -0x1ab).`

We should probably have filtered this out in `validFuncOffset` anyway?

**Comment by sei-eschwartz** [comment]
For posterity's sake, I should mention that @sei-ccohen and I discussed this offline and negative offsets are possible and valid in the presence of multiple inheritance.

I am currently testing Gw.exe with my proposed changes in #204.

**Comment by sei-eschwartz** [comment]
With my proposed changes, the negative offset is not there.  I haven't tested with our private pharos branch, which has a lot of commits we haven't published yet (though we're working on that), to see if it's actually fixed by my commit.

**Comment by Jonathan-Greve** [comment]
Good work! I should be able to test it out tomorrow (or within a few days) and report back. Looking forward to what else you have in store in the future. This program has already been a great boon to me.

**Comment by Jonathan-Greve** [comment]
I still get the negative offset. Is it because the docker image has not been updated with your commit?

**Comment by sei-eschwartz** [comment]
Yes, the changes are not public yet. We may release them later today, but probably without my commit since I am still testing. I can push it as a branch though.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sei-eschwartz** [comment]
The new version is out if you want to try it.

**Comment by sei-eschwartz** [comment]
The new version is out if you want to try it.

**Comment by sei-eschwartz** [comment]
Although you may want to wait until we fix the CI if you are using the Docker image.

**Comment by sei-eschwartz** [comment]
Docker image is finally rebuilt if you want to try it.

I have confirmed that my new commit does not actually change anything in the new release.

**Comment by Jonathan-Greve** [comment]
Finally got around to running OOAnalyzer again. And I am happy to report that it worked perfectly. No more negative offset 👍

**Comment by sei-eschwartz** [comment]
Great! Thanks for letting us know.  Also please do let us know if you see anything that "looks wrong" in your executable.
